### ISSUE TITLE
Not updated to Xcode 11

### ISSUE THREAD

**Issue by thom-bahm** [mythxn/DesignCode#4]
@ObjectBinding has been deprecated to @ObservedObject or @EnvironmentObject, Not entirely sure; either way @ObjectBinding is no longer available for Xcode11.

**Comment by thom-bahm** [comment]
Also, TabbedView{} is outdated, among other things which Im currently looking for; Ill try to fix what I can .

**Comment by michaelmorehead** [comment]
for the statusBarHeight issue: 'statusBarFrame' was deprecated in iOS 13.0: 
Use the statusBarManager property of the window scene instead.

// let statusBarHeight = UIApplication.shared.statusBarFrame.height

let window = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
let statusBarHeight = window?.windowScene?.statusBarManager?.statusBarFrame.height ?? 0

**Comment by shamil-chomaev** [comment]
Can anyone send a working version of the project?

**Comment by luckychris** [comment]
i updated it - it runs (but of course no guarantee...
check this out: https://github.com/luckychris/DesignCode-SwiftUI

**Comment by thom-bahm** [comment]
thanks for doing that, Think this issues done.
