### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ZClee128** [mythxn/DesignCode#5]
Hasn't the official version of xcode11 been updated? There are a lot of codes that can't be used. Please update them.

**Comment by kyleturner** [comment]
@ZClee128 It really doesn't take much more than 15 minutes to comment out the offending areas, do some guessing on what the new namespaces have been changed to, and Google a few things in SwiftUI to understand what needs to be changed. I have the app running in the latest Xcode 11. It's the least someone can do to learn SwiftUI for the hard work the creators put into this!

**Comment by shamil-chomaev** [comment]
Can anyone send a working version of the project?

**Comment by luckychris** [comment]
i updated it - it runs (but of course no guarantee...
check this out: https://github.com/luckychris/DesignCode-SwiftUI

**Comment by ryanoff** [comment]
@luckychris, thanks. This is working for me in Xcode 11.1. Mostly.
